using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;

namespace CIDM3312Final.Models;

public static class SeedData
{
    public static void Initialize(IServiceProvider serviceProvider)
    {
        using var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());

        if (context.Games.Any())
        {
            return;
        }

        context.Games.AddRange(
            new Game { Title = "Borderlands", ReleaseDate = DateTime.Parse("10/20/2009"), Genre = "Action role-playing, First-person shooter", GameCover = "img/borderlands.jpg" },
            new Game { Title = "Cyberpunk 2077", ReleaseDate = DateTime.Parse("12/10/2020"), Genre = "Action role-playing", GameCover = "img/Cyberpunk_2077.jpg" },
            new Game { Title = "South Of Midnight", ReleaseDate = DateTime.Parse("04/03/2025"), Genre = "Action-adventure", GameCover = "img/South.jpg" },
            new Game { Title = "Red Dead Redemption 2", ReleaseDate = DateTime.Parse("10/26/2018"), Genre = "Western, Shooter game, Action-adventure game,", GameCover = "img/RDR2.jpg" },
            new Game { Title = "God Of War", ReleaseDate = DateTime.Parse("04/20/2018"), Genre = "Action-adventure game, Fighting game", GameCover = "img/GOW.jpg" }
        );

        context.SaveChanges();

        context.Characters.AddRange(
        new Character { CharacterName = "Roland", CharacterStory = "Only the most elite military training can produce a soldier like Roland, who's always ready to charge into battle using whatever firearms are currently on-hand. Roland brings his own backup in the form of the Scorpio Turret Action Skill, which lays down covering fire and can even heal injured teammates.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Lilith", CharacterStory = "Lilith possesses otherworldly abilities. Her Phasewalk Action Skill temporarily renders her invisible, allowing her to navigate the battlefield with ease. Once she emerges, Lilith releases a massive burst of energy, devastating any enemies nearby.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Modecai", CharacterStory = "Mordecai prefers to pick off his targets from a distance, whether that's with an impeccably aimed sniper shot or the talons of his loyal pet raptor, Bloodwing. Activating the Bloodwing Action Skill sends Mordecai's feathered friend swooping down to eviscerate any enemy in his sights.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Brick", CharacterStory = "Brick's fists are as lethal as any firearm, and his hulking, muscle-packed frame makes him a tough target to take down. When activating his Berserk Action Skill, Brick flies into an uncontrollable rage, regaining health at a staggering rate as he punches his opponents to death.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Maya", CharacterStory = "Raised by a manipulative order of warrior-monks, Maya is a master of elemental damage. Her Phaselock Action Skill traps enemies in a stasis sphere—giving her and other Vault Hunters plenty of time to fill them with holes.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Axton", CharacterStory = "A bad man with a very bad turret, Axton brings a lethal set of commando skills to the table. His Sabre Turret Action Skill doles out serious damage and can be outfitted with a wide range of artillery", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Salvador", CharacterStory = "This Pandoran native exhibits much of the local exuberance for violence and (alleged) criminal activity. Activating Salvador's Gunzerking Action Skill lets him dual-wield two weapons for double the firepower and an exponentially higher body count.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "Zero", CharacterStory = "The most effective assassin to ever operate in the galaxies, Zer0 is skilled with everything from long-range rifles to his digistructed blade. Upon activating his Decepti0n Action Skill, Zer0 cloaks, leaving behind a holographic decoy in his place that opens up unsuspecting enemies to devastating sneak attacks.", Game = context.Games.Where(m => m.Title == "Borderlands").Single()},
        new Character { CharacterName = "V", CharacterStory = "Roaming the Badlands, looting scrapyards, raiding fuel depots - life on the road wasn't easy. But growing up in a nomad clan has its perks. Honesty, integrity, and a love of freedom - qualities that few in Night City possess, and no amount of money can buy.", Game = context.Games.Where(m => m.Title == "Cyberpunk 2077").Single() },
        new Character { CharacterName = "Johnny Silverhand", CharacterStory = "a famous and influential rockerboy and lead singer of the band Samurai before its breakup in 2008.[2] A military veteran who defined the rockerboy movement as it is known today, Silverhand was the most prominent figure who fought against the corrupt American government and megacorporations, often being described as a terrorist because of this. Despite being charismatic and quite the charmer, he was also known to be irrational, impulsive, and manipulative.",Game = context.Games.Where(m => m.Title == "Cyberpunk 2077").Single()},
        new Character { CharacterName = "Jackie Welles", CharacterStory = "A proud son of Heywood and an even prouder son of Mamá Welles. Jackie's stubborn - when he wants something, he won't stop (or shut up about it) until he gets his hands on it. Jackie always wanted a lot out of life - maybe too much.", Game = context.Games.Where(m => m.Title == "Cyberpunk 2077").Single()},
        new Character { CharacterName = "Panam Palmer", CharacterStory = "Panam is a nomad - although, maybe 'ex-nomad' rings truer these days. She locked horns with the family's leader, Saul, left Aldecaldo nation and moved to Night City to try her luck as a merc. Panam's life is at a crossroads - on one hand she knows her life needs a change, it's now or never. On the other hand, burning bridges with the nomad family where all her friends are might have been a bit drastic. On top of that, Night City doesn't take too kindly to nomads or have patience for people like Panam who are internally conflicted and dream of a brighter future.", Game = context.Games.Where(m => m.Title == "Cyberpunk 2077").Single() },
        new Character { CharacterName = "Judy Alvarez", CharacterStory = "One of braindance's most gifted editors and a skilled techie. If she wanted to, she could get hired at any corpo entertainment studio and make bank, but Judy values her independence too much to sell out — she rejects every offer that comes her way. Her anarchist spirit drew her to the Mox in the hope that they could improve the lives of people in Night City. Her biggest flaw is that she can't keep her mouth shut in the face of injustice — something that always gets her in trouble. For some, though, it's her greatest virtue.", Game = context.Games.Where(m => m.Title == "Cyberpunk 2077").Single()},
        new Character { CharacterName = "Hazel Flood", CharacterStory = "Hazel is the protagonist and the player character of South of Midnight. She is a young woman with magical powers who is from Prospero, a town in the American Deep South that was destroyed from a hurricane.", Game = context.Games.Where(m => m.Title == "South Of Midnight").Single()},
        new Character { CharacterName = "Catfish", CharacterStory = "Catfish is a large, ancient, and wise mythical creature and a key ally to the protagonist, Hazel. He features patchwork scales, a distinct eye, and aids Hazel on her journey by sharing knowledge about her powers as a Weaver and the world of Southern folklore. He is not the same character as Roux. ", Game = context.Games.Where(m => m.Title == "South Of Midnight").Single()},
        new Character { CharacterName = "Crouton", CharacterStory = "Hazel little stuffed companion", Game = context.Games.Where(m => m.Title == "South Of Midnight").Single()},
        new Character { CharacterName = "Arthur Morgan", CharacterStory = "Arthur Morgan is a cold, brooding outlaw who often resorts to violence and has very few qualms about killing. At his worst Arthur could be extremely ruthless and completely unsympathetic to the people he hurts. Despite being capable of committing such violence, Arthur does have a playful, comedic side to his personality that comes out around those he is friendly with. Thus, he isn't above joking or employing sarcasm with his friends. Notably, Arthur was kind and polite to John Marston's then-four-year-old son, Jack, having a gentle demeanor around the young boy in contrast to his threatening persona.", Game = context.Games.Where(m => m.Title == "Red Dead Redemption 2").Single()},
        new Character { CharacterName = "John Marston", CharacterStory = "John is a fairly serious individual with very little patience for the eccentricities of both life and the various people he meets during the events of Red Dead Redemption. He frequently threatens Irish into sobering up so as to be of some use to him, and he is clearly disturbed/disgusted by Seth's habitual grave robbing. However, he is not above employing sarcasm in conversation with certain characters, particularly those he sees as exhibiting hypocrisy, which can be seen in his interactions with both Abraham Reyes and Agustin Allende. John is also shown assisting both sides of the revolution in Mexico, suggesting he is willing to be morality apathetic to save his family.  ", Game = context.Games.Where(m => m.Title == "Red Dead Redemption 2").Single()},
        new Character { CharacterName = "Dutch van der linde", CharacterStory = "Dutch seems to carry a philosophy similar to other characters in the Red Dead Redemption saga. Dutch has an anarchistic worldview and seems to want a world that goes somewhere along the lines of a Hunter-Gatherer Society, one that opposes technology and governmental control where one must fight to survive but may also live the lifestyle they choose, free from any rules and regulations; a world where men live very much like they did in the old, idealized Wild West. ", Game = context.Games.Where(m => m.Title == "Red Dead Redemption 2").Single()},
        new Character { CharacterName = "Abigail Roberts", CharacterStory = "Abigail is shown to be a motherly and protective woman. She's strong-willed, independent, and loves her family dearly and can be quite strict at times. She often finds herself at odds with John, disliking her husband's habits of endangering himself and the family in the name of revenge and redemption, not wanting to become a widow and more importantly, leaving their son fatherless.", Game = context.Games.Where(m => m.Title == "Red Dead Redemption 2").Single() },
        new Character { CharacterName = "Hosea Matthews", CharacterStory = "Hosea is an intelligent outlaw in touch with his wits, having worked as a con artist and a thief for over two decades. He appears to be a slick talker, using his brains to get into and out of any situation at hand. Unlike Arthur or Dutch, Hosea prefers not to use violence as a means of obtaining money. ", Game = context.Games.Where(m => m.Title == "Red Dead Redemption 2").Single()},
        new Character { CharacterName = "Kratos", CharacterStory = "Kratos was originally an incredibly destructive, ruthless, violent, fierce, brave, and brutal warrior who is focused mainly on his own goals, and turning what guilt he has into anger. Whenever he is wronged, he becomes obsessed with revenge and will destroy who or whatever he has to get his vengeance. ", Game = context.Games.Where(m => m.Title == "God Of War").Single()},
        new Character { CharacterName = "Atreus", CharacterStory = "Introduced as the son of Kratos and Faye, Atreus joins his father on a journey to spread his deceased mother's ashes on top of the highest peak in all the Nine Realms. On their journey, Kratos teaches Atreus how to survive and fight as a warrior while Atreus teaches Kratos to open up to those that can help them.", Game = context.Games.Where(m => m.Title == "God Of War").Single()},
        new Character { CharacterName = "Mimir", CharacterStory = "The figure of expansive knowledge and wisdom who claims to be the 'Smartest Man Alive'. He was banished to Midgard and sealed in a tree by Odin. Kratos cuts his head off and has been later successfully reanimated by Freya, after which he starts serving as the guide of Kratos and Atreus.", Game = context.Games.Where(m => m.Title == "God Of War").Single()},
        new Character { CharacterName = "Freya", CharacterStory = "Encountered shortly after Kratos and Atreus embark on their adventure. She immediately senses that Kratos is a God. She assist the pair on their adventure, assisting them in traveling between the Norse World. Later, she is revealed to be Freya, one of the Vanir Gods and ex-wife of Odin who banished her to Midgard and left her incapable of leaving or harming others and also robbed her of her Valkyrie abilities.", Game = context.Games.Where(m => m.Title == "God Of War").Single()}
        );
        
        context.SaveChanges();
    }
}
